### ISSUE TITLE
How to actually use?

### ISSUE THREAD

**Issue by CallMeCostco** [FelixReuthlinger/ConfigureToolTier#1]
hi, ive done all the steps that i can tell, have the org.bepinex.configure.tool.tier in my bepinex config folder with the adjusted values i want in game but when i load up the game it hasnt changed, im not totally sure what im missing in order for the game to use these values. ofc i also have the dll file in the plugins folder

**Comment by FelixReuthlinger** [comment]
did it log anything to your console? it will for example tell about a config file found and about issues loading configs if you did create something that would not work.

In general and of course, this mod does maybe not work if you are using other mods that do conflicting things.
